spring.application.name=train_transport_customer_service

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/train_tickets
spring.datasource.username=train_user
spring.datasource.password=train_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
